"""Removed category field in problems table

Revision ID: 4e1bed22123d
Revises: 0160ebb1d3fb
Create Date: 2024-09-16 21:25:38.852668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e1bed22123d'
down_revision: Union[str, None] = '0160ebb1d3fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('category', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
