# Generated by Django 5.1.5 on 2025-01-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('problemset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='problems_solved',
            field=models.ManyToManyField(related_name='users_solved', to='problemset.problem'),
        ),
        migrations.AddField(
            model_name='user',
            name='problems_unsolved',
            field=models.ManyToManyField(related_name='users_unsolved', to='problemset.problem'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
