# Generated by Django 5.1.5 on 2025-03-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('problemset', '0002_submission_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='problems_solved',
            field=models.ManyToManyField(blank=True, related_name='users_solved', to='problemset.problem'),
        ),
        migrations.AlterField(
            model_name='user',
            name='problems_unsolved',
            field=models.ManyToManyField(blank=True, related_name='users_unsolved', to='problemset.problem'),
        ),
    ]
