# Generated by Django 5.1.5 on 2025-03-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.CharField(default='', max_length=65536),
        ),
    ]
