# Generated by Django 5.1.5 on 2025-03-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0005_alter_problem_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.TextField(default='', max_length=65536),
        ),
    ]
