# Generated by Django 6.0.1 on 2026-01-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0008_alter_submission_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
