# Generated by Codex on 2026-06-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problemset", "0009_submission_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="JudgeJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("attempt", models.PositiveIntegerField(default=0)),
                ("claimed_by", models.CharField(blank=True, max_length=128)),
                (
                    "lease_expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "last_heartbeat_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judge_jobs",
                        to="problemset.submission",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(status__in=["queued", "running"]),
                        fields=("submission",),
                        name="uniq_active_judge_job",
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=["status", "lease_expires_at"],
                        name="judgejob_status_lease_idx",
                    ),
                    models.Index(
                        fields=["submission", "status"],
                        name="judgejob_submission_status_idx",
                    ),
                ],
            },
        ),
    ]
