# Generated by Django 5.1.5 on 2025-03-19 02:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='short_info',
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='info',
            field=models.TextField(default='Placeholder text'),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='salary_range',
            field=models.JSONField(default=dict),
        ),
    ]
