# Generated by Django 5.1.5 on 2025-03-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0002_remove_job_job_id_remove_job_short_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='Remote', max_length=200),
        ),
    ]
